#pragma once
#define TEST_ALL

#ifdef TEST_ALL

#define TEST_MONTHLY_DATA
#define TEST_FILE_READER
#define TEST_OUTPUT_FORMAT
#define TEST_GET_FOOTFALLS_FROM_CSV
#define TEST_GENERATE_TIMESTAMPS
#define TEST_PRINT_OUTPUT
#define TEST_MONTHLY_TIMESTAMPS

#endif
