name: Build Run Sender

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: build sender
      run: g++ -Wall -Wextra -Werror --coverage -o SenderOutput Sender/*.cpp
      
    - name: run sender
      run: ./SenderOutput
      
    - name: sender coverage report
      run: gcov -r Sender/*.cpp  
